import requests
from requests_oauthlib import OAuth1Session
import json
import time
from datetime import datetime
import math

# generated by twitter when registering project with twitter api

consumer_key = api_key
consumer_secret = api_secret_key

last_michigan_championship = datetime(2004, 11, 20, 16, 43)
print(str(last_michigan_championship.year))
now = datetime.now()
difference = datetime.now() - last_michigan_championship
years = math.floor(difference.days / 365.25)
days = math.floor(difference.days - (years * 365.25))
hours = difference.seconds // 3600
minutes = (difference.seconds // 60) % 60




def build_url(name, bio):
    # add the time to the beginning of the bio
    t = time.localtime()
    hour = t.tm_hour % 12
    minute = t.tm_min
    time_phrase = f"The current time is {hour}:{minute+1} and it has been {years} years, {days} days, {hours} hours, and {minutes} minutes since Michigan football last won a B1G championship."
    
    # remove plurals if time increments are 1
    if years == 1:
        time_phrase = time_phrase.replace('years', 'year')
    if days == 1:
        time_phrase = time_phrase.replace('days', 'day')
    if hours == 1:
        time_phrase = time_phrase.replace('hours', 'hour')
    if minutes == 1:
        time_phrase = time_phrase.replace('minutes', 'minute')

    bio = time_phrase + bio
    print(bio)

    url = 'https://api.twitter.com/1.1/account/update_profile.json?name=' + name + '&description=' + bio
    # how you indicate spaces in url
    url = url.replace(' ', '%20') # html encoding for space is %20
    url = url.replace(':', '%3A').replace('%3A', ':', 1) # html encoding for : is %3A, but we don't want the first colon replaced in https://
    print(url)

    return url

for i in range(100):
    oauth = OAuth1Session(
        consumer_key,
        client_secret=consumer_secret,
        resource_owner_key=access_token,
        resource_owner_secret=access_token_secret,
    )
    response = oauth.post(build_url("AJ Bensman", ""))
    time.sleep(60)